=== nickshrestha/nick/projects/catalog_19031183.dtd
<!ELEMENT MusicStore (storeInfo, music)>
<!ELEMENT storeInfo (logo, storeName, address, telephone_number, website)>
<!ELEMENT logo (#PCDATA)>
<!ELEMENT storeName (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT telephone_number (#PCDATA)>
<!ELEMENT website (#PCDATA)>
<!ELEMENT music (category, song+)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT song (name, image, genre, album, length, releaseDate, singers?, record?, songWriters?, producers?, directors?, discription?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT album (#PCDATA)>
<!ELEMENT length (#PCDATA)>
<!ELEMENT releaseDate (#PCDATA)>
<!ELEMENT singers (title1, singer+)>
<!ELEMENT title1 (#PCDATA)>
<!ELEMENT singer (#PCDATA)>
<!ELEMENT record (title2, recorded+)>
<!ELEMENT title2 (#PCDATA)>
<!ELEMENT recorded (#PCDATA)>
<!ELEMENT songWriters (label, writer+)>
<!ELEMENT label (#PCDATA)>
<!ELEMENT writer (#PCDATA)>
<!ELEMENT producers (title4, producer+)>
<!ELEMENT title4 (#PCDATA)>
<!ELEMENT producer (#PCDATA)>
<!ELEMENT directors (title5, director)>
<!ELEMENT title5 (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT discription (#PCDATA)>
<!ATTLIST song songId ID #REQUIRED>
<!ATTLIST image imageId ID #REQUIRED>

=== nickshrestha/nick/projects/catalog_19031183.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!-- css -->
<?xml-stylesheet type="text/css" href="catalog_19031183.css"?>

<!-- DTD-->
<!DOCTYPE MusicStore SYSTEM "catalog_19031183.dtd"[]>

<!-- Schema -->
<MusicStore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
			xsi:noNamespaceSchemaLocation="catalog_19031183.xsd">    

    <!-- Store -->
    <storeInfo>
        <logo></logo>
        <storeName>Royalty Music Store</storeName>
        <address>Putalisadak, Kathmandu</address>
        <telephone_number>016613496</telephone_number>
        <website>https://Royalitymusicstore.com</website>
    </storeInfo>

    <!-- Musics-->
    <music>
        <category>Music List</category>
        <song songId='S1'>
            <name>Heartbreak Anniversary</name>
            <image imageId='I1'></image>
            <genre>Genre:Soul</genre>
            <album>Album: Giveon</album>
            <length>Length: 03:16</length>
            <releaseDate>Release Date: March 3, 2021</releaseDate>
            <singers>
                <title1> Singers</title1>
                <singer>Giveon</singer>
            </singers>
            <record>
                <title2>Recorded By</title2>
                 <recorded>Nick Records</recorded>
            </record>
            <songWriters>
                <label>Writers</label>
                <writer>Giveon</writer>
            </songWriters>
            <producers>
                <title4> Producer </title4>
                 <producer>Dukes</producer>
            </producers>
            <directors> 
                <title5> Director </title5>
                <director> Krimson Kane </director>
            </directors>
            <discription>Heartbreak Anniversary is a song by American singer-songwriter Giveon. It was released on February 
            21, 2020, as the second single from his debut EP, Take Time (2020). Written from the perspective of a friend of Giveon's,
             the downtempo piano ballad finds him singing about the date of a breakup, reminiscing and grieving about a love gone wrong. 
             The song garnered chart success in early 2021, with a music video subsequently being released, 
            and the song sent to US radio, in March 2021. It has so far reached number one in Malaysia and Singapore.</discription>
        </song>

        <song songId='S2'>
            <name>See You Again</name>
            <image imageId='I2'></image>
            <genre>Genre: Hip-Hop/Rap</genre>
            <album>Album: Furious 7: Original Motion Picture Soundtrack</album>
            <length>Length: 03:57</length>
            <releaseDate>Release Date: April 7, 2015</releaseDate>
            <singers>
                <title1> Singers</title1>
                <singer>Wiz Khalifa,</singer>
                <singer>Charlie Puth</singer>
            </singers>
            <record>
                <title2>Recorded By</title2>
                 <recorded> Wanner Brothers</recorded>
            </record>
            <songWriters>
                <label>Writers</label>
                <writer>Wiz Khalifa,</writer>
                <writer>Charlie Puth</writer>
            </songWriters>
            <producers>
                <title4> Producer </title4>
                 <producer> DJ Frank E</producer>
            </producers>
            <directors> 
                <title5> Director </title5>
                <director> chris back</director>
            </directors>
            <discription>See You Again is a song by American rapper Wiz Khalifa, featuring American singer Charlie Puth. 
            The track was commissioned for the soundtrack of the 2015 action film Furious 7 as a tribute to actor Paul Walker, 
            who died in a single-vehicle accident on November 30, 2013, in Valencia, California. Later on, the song was included
             as a bonus track on the international release of Puth's debut album, Nine Track Mind. The artists co-wrote the song with 
             its co-producers, DJ Frank E and Andrew Cedar, with additional production from Puth and mixing provided by Manny Marroquin.
             "See You Again" was released on March 10, 2015, as the soundtrack's lead single in the United States.</discription>
        </song>
	    
        <song songId='S3'>
            <name>Billie Jean</name>
            <image imageId='I3'></image>
            <genre>Genre: Post-disco, funk and dance pop</genre>
            <album>Album: Thriller</album>
            <length>Length: 04:54</length>
            <releaseDate>Release Date: January 2, 1983</releaseDate>
            <singers>
            	<title1>Singer</title1>
                <singer>Michael Jackson</singer>
            </singers>
             <record>
            <title2>Recorded By</title2>
            <recorded>Epic</recorded>
            </record>
            <songWriters>
                <label>Writers</label>
                <writer>Michael Jackson</writer>
            </songWriters>
            <producers>
                <title4> Producer </title4>
                 <producer>Quincy Jones</producer>
            </producers>
            <directors> 
                <title5> Director </title5>
                <director> kisonli </director>
            </directors>
            <discription>Billie Jean is a song by American singer Michael Jackson, released by Epic Records on January 2, 1983, as 
            the second single from Jackson's sixth studio album, Thriller (1982). It was written and composed by Jackson and produced 
            by Jackson and Quincy Jones. "Billie Jean" blends post-disco, rhythm and blues, funk and dance-pop. The lyrics describe a 
            woman, Billie Jean, who claims that the narrator is the father of her newborn son, which he denies. 
            Jackson said the lyrics were based on groupies' claims about his older brothers when he toured with them as the Jackson 5.</discription>
        </song>

        <song songId='S4'>
            <name>The Lazy Song</name>
            <image imageId='I4'></image>
            <genre>Genre: Reggae-pop</genre>
            <album><![CDATA[Album: Doo-Wops & Hooligans]]></album>
            <length>Length: 03:15</length>
            <releaseDate>Release Date: February 15, 2011</releaseDate>
            <singers>
            	<title1>Singer</title1>
                <singer> Bruno Mars</singer>
            </singers>
             <record>
            <title2>Recorded By</title2>
            <recorded>dellon duke</recorded>
            </record>
            <songWriters>
                <label>Writers</label>
                <writer> Bruno Mars,</writer>
                <writer>Philip Lawrence,</writer>
                <writer>K'naan,</writer>
                <writer>Ari Levine</writer>
            </songWriters>
            <producers>
                <title4> Producer </title4>
                 <producer>bruno Mars</producer>
            </producers>
             <directors> 
                <title5> Director </title5>
                <director> The Smeezingtons</director>
            </directors>
            <discription><![CDATA["The Lazy Song" is a song by American singer-songwriter Bruno Mars for his debut studio album
             Doo-Wops & Hooligans (2010). It was serviced to contemporary hit radios in the United States on February 15,
              2011 as the album's third single by Atlantic and Elektra. Development of "The Lazy Song" began while Mars, Philip Lawrence and
               Ari Levine were hanging around the studio and didn't feel like working. The trio, produced the track under their alias, the Smeezingtons,
                and wrote the song in collaboration with singer-songwriter K'naan. Musically, "The Lazy Song" has been described as borrowing 
            "heavily from roots reggae" and has been compared to the reggae style of Jason Mraz, while lyrically it is an anthem to laziness.]]></discription>
        </song>

        <song songId='S5'>
            <name>Nothing Else Matters</name>
            <image imageId='I5'></image>
            <genre>Genre: Electronic Dance Music</genre>
            <album>Album: Metallica</album>
            <length>Length: 06:28</length>
            <releaseDate>Release Date: April 20, 1992</releaseDate>
            <singers>
            	<title1>Singer</title1>
                <singer>Anne Marie</singer>
            </singers>
            <record>
            <title2>Recorded By</title2>
            <recorded>Atlantic Studio</recorded>
            </record>
            <songWriters>
            	<label>Writer</label>
                <writer>James Hetfield,</writer>
                <writer>Lars Ulrich</writer>
            </songWriters>
            <producers>
            <title4>Producer </title4>
            <producer>Bob Rock</producer>
            </producers>
            <directors> 
                <title5> Director </title5>
                <director> Paul Minati</director>
            </directors>
            <discription>"Nothing Else Matters" is a song by American heavy metal band Metallica.
             It was released in 1992 as the third single from their self-titled fifth studio album, Metallica. 
             The song peaked at number 11 on the Billboard Mainstream Rock Tracks chart, number 6 on the UK Singles Chart,
              number 1 in Denmark, and reached the top ten on many other European charts. "Nothing Else Matters" was featured as 
              a playable track in the music video game Guitar Hero: Metallica. Recognized as one of Metallica's best known and most popular songs,
             the power ballad[1] has become a staple in live performances.</discription>
        </song>

        <song songId='S6'>
